# Generated by Django 5.0.3 on 2024-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('primary_actor', models.CharField(max_length=200)),
                ('secondary_actor', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('synopsis', models.CharField(max_length=600)),
                ('img_url', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('seasons', models.CharField(max_length=10)),
                ('actor', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('synopsis', models.CharField(max_length=600)),
                ('img_url', models.CharField(max_length=999)),
            ],
        ),
    ]
