# Generated by Django 5.0.3 on 2024-04-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
