# Generated by Django 5.0.3 on 2024-04-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0002_alter_movie_synopsis_alter_series_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='synopsis',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='synopsis',
            new_name='message',
        ),
    ]
